apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::632919071643:user/github-ci 
      username: github-ci 
      groups: 
        - system:masters
