apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytodo-api-deployment
  labels:
    app: easytodo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytodo-api
  template:
    metadata:
      labels:
        app: easytodo-api
    spec:
      containers:
      - name: easytodo-api
        image: 632919071643.dkr.ecr.ap-south-1.amazonaws.com/easytodo:ca320fc94c1a570465b02b6ba620519f48f6559c
        ports:
        - containerPort: 80