version: '3.8'

services:
  app:
    image: prashanthdevaraj/easytodo-backend:latest

    # Overrides default command so things don't shut down after the process ends.
    command: python /workspace/manage.py runserver 0.0.0.0:80